# Generated by Django 5.0.7 on 2024-08-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ambulance', '0001_initial'),
        ('Crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulanceCombileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AmbulanceLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambulance.ambulancelocation')),
                ('ambulanceDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ambulance.ambulancedetail')),
            ],
        ),
        migrations.CreateModel(
            name='crewCombineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callCrewDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crew.callcrew')),
                ('trafficCrewDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crew.trafficcrew')),
                ('trafficCrewStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crew.trafficcrewavailable')),
            ],
        ),
    ]
