# Generated by Django 5.0.7 on 2024-08-10 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100)),
                ('caller_phonenumber', models.CharField(max_length=15)),
                ('patients_number', models.CharField(max_length=15)),
                ('patients_condition', models.TextField()),
                ('available_for_ambulance', models.BooleanField()),
                ('patient_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
