# Generated by Django 5.0.7 on 2024-08-10 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crew', '0001_initial'),
        ('Work', '0002_calldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetails',
            name='assigned_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_calls', to='Crew.trafficcrew'),
        ),
    ]
