# Generated by Django 5.0.7 on 2024-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crew', '0001_initial'),
        ('Work', '0003_calldetails_assigned_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetails',
            name='assigned_crew',
        ),
        migrations.AddField(
            model_name='calldetails',
            name='assigned_crew',
            field=models.ManyToManyField(blank=True, related_name='assigned_calls', to='Crew.trafficcrew'),
        ),
    ]
