# Generated by Django 5.0.7 on 2024-08-10 07:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDetail',
            fields=[
                ('amb_id', models.CharField(editable=False, help_text='Unique ambulance id', max_length=50, primary_key=True, serialize=False)),
                ('amb_num', models.CharField(help_text='Ambulance plate number', max_length=20, unique=True)),
                ('amb_cap', models.PositiveIntegerField(help_text='Number of patients an ambulance can carry')),
                ('amb_hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceLocation',
            fields=[
                ('amb_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Ambulance.ambulancedetail')),
                ('amb_loc', django.contrib.gis.db.models.fields.PointField(help_text='live gps location of the ambulance', srid=4326)),
            ],
        ),
    ]
